version: '3.7'

services:
  db:
    image: postgres:11.2
    volumes:
      - ../volume:/var/lib/postgresql
    environment:
      - POSTGRES_USER=lucas
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=recipeapi
    networks:
      - my-network

  pgadm:
    image: dpage/pgadmin4
    links:
      - db:db
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "root"
      PGADMIN_DEFAULT_PASSWORD: "toor"
    depends_on:
      - db
    networks:
      - my-network
  recipe:
    build:
      dockerfile: ./devops/docker/Dockerfile
      context: ../../
    image: lucas/recipe
    ports:
      - "8080:8080"
    networks:
      - my-network
    depends_on:
      - db

networks:
  my-network:
    driver: bridge